[db]
driver     = "sqlite3"
datasource = "dev.db"

[ctcp]
enablegit = false

[forecast]
key = ""

[github]
token = ""

[net_tools]
key = ""

[twitter]
consumerkey       = ""
consumersecret    = ""
accesstoken       = ""
accesstokensecret = ""

# https://developers.google.com/youtube/registering_an_application
[youtube]
key               = ""

