kind: pipeline
name: default

steps:
- name: docker
  depends_on: [ clone ]
  image: plugins/docker
  settings:
    repo: belak/seabird
    dockerfile: Dockerfile
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
