workspace:
  base: /go
  path: src/github.com/belak/go-seabird

pipeline:
  test:
    image: golang:1.10-alpine
    commands:
      - apk add --update git
      - go get -t ./...
      - go test -v ./...
      - cd ./cmd/seabird && go build
      - go get github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter ./...

  docker:
    image: plugins/docker
    repo: belak/seabird
    dockerfile: Dockerfile
    tag: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

