workspace:
  base: /go
  path: src/github.com/belak/go-seabird

pipeline:
  test:
    image: golang:1.10
    commands:
      # Test first
      - go get -t ./...
      - go test -v ./...
      - cd ./cmd/seabird && go build
      # Linting second
      - go get github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter ./... --fast -D dupl -D gas -D gconst --cyclo-over 15

  docker:
    image: plugins/docker
    repo: belak/seabird
    dockerfile: Dockerfile
    tag: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

