workspace:
  base: /go
  path: src/github.com/belak/go-seabird

pipeline:
  test:
    image: golang:1.11-alpine
    commands:
      # Testing
      - apk add -U --no-cache build-base git
      #- go get -u golang.org/x/vgo
      #- vgo test ./...
      # Linting
      - go get -u github.com/alecthomas/gometalinter
      - gometalinter --install
      # NOTE: This is a dirty hack until gometalinter gets better support for
      # running linters using vgo. Also note that gotype has been disabled (as
      # the same errors should be caught by the build above) until it's fixed
      # with vgo support.
      #- ln -s `which vgo` /go/bin/go
      - gometalinter ./...
      - rm -f /go/bin/go

  build:
    image: golang:1.11-alpine
    commands:
      - apk add -U --no-cache build-base git
      - go build -o ./dist/seabird ./cmd/seabird

  docker:
    image: plugins/docker
    repo: belak/seabird
    dockerfile: Dockerfile
    tag: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

