pipeline:
  test:
    image: golang:1.10
    commands:
      - go get github.com/alecthomas/gometalinter
      - go get -t ./...
      - gometalinter ./... --fast -D dupl -D gas -D gconst --cyclo-over 15
      - go test -v ./...
      - cd ./cmd/seabird && go build

  docker:
    image: plugins/docker
    repo: belak/seabird
    dockerfile: Dockerfile
    tag: latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

