linters:
  enable-all: true
  disable:
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - godox
    - gomnd
    - lll
    - prealloc
    - stylecheck
    - unparam
    - wsl

    # Newer linters should be investigated
    - goerr113
    - nestif

linters-settings:
  goimports:
    local-prefixes: github.com/belak/go-seabird
  govet:
    check-shadowing: true
