language: go
go:
  - '1.11'
  - stable
env:
  - GO111MODULE=on

before_install:
  - GO111MODULE=off go get -u github.com/Quasilyte/go-consistent
  - GO111MODULE=off go get -u github.com/alecthomas/gometalinter
  - GO111MODULE=off gometalinter --install

script:
  # Test
  - go test -v ./...

   # Linting
  - $HOME/gopath/bin/gometalinter ./...
  - go vet ./...
  - go vet --shadow ./...
  - go-consistent ./...

  # Build
  - go build ./cmd/seabird/*.go
  - go build ./cmd/seabird-migrate/*.go
