language: go
go: '1.10'

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -t ./...

script:
  - gometalinter ./...
  - go test -v ./...
  - cd ./cmd/seabird && go build
