language: go
go: 1.8

before_install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - go get -t ./...

script:
  - gometalinter ./... --fast -D dupl -D gas -D goconst --cyclo-over=12
  - go test -v ./...
  - cd ./cmd/seabird && go build
