[core]
# Connection info
host          = "chat.freenode.net:6697"
tls           = true
tls_no_verify = false

# User info
nick = "HelloWorld"
user = "seabird"
name = "seabird"
pass = "qwertyasdf"

# Global config
prefix = "!"

# Startup commands
cmds = [
  "JOIN #encoded"
]

plugins = [
  "chance"
]
