[core]
pidfile = "/var/run/seabird/seabird.pid"

# Connection info
host          = "chat.freenode.net:6697"
tls           = true
tlsnoverify   = false

# User info
nick = "HelloWorld"
user = "seabird"
name = "seabird"
pass = "qwertyasdf"

# Global config
prefix = "!"

# Startup commands
cmds = [
  "JOIN #encoded"
]

plugins = [
  "db",
  "chance",
  "url",
  "url/*"
]
