[core]
pidfile = "/var/run/seabird/seabird.pid"

# Connection info
host          = "chat.freenode.net:6697"
tls           = true
tlsnoverify   = false

# User info
nick = "HelloWorld"
user = "seabird"
name = "seabird"
pass = "qwertyasdf"

# Global config
prefix = "!"

# Startup commands
cmds = [
  "JOIN #encoded"
]

plugins = [
  "db",
  "chance"
]

[influxdb]
enabled = false
url = "https://my-influx-url.com"
database = "my-db"
precision = "s"
username = "username"
password = "password"
submitinterval = 10

[db]
driver = "sqlite3"
datasource = "dev.db"

[ctcp]
enablegit = false

[forecast]
key = ""

[github]
token = ""

[net_tools]
key = ""

[tiny]
key = ""

[twitter]
consumerkey       = ""
consumersecret    = ""
accesstoken       = ""
accesstokensecret = ""

# https://developers.google.com/youtube/registering_an_application
[youtube]
key               = ""

