// Code generated by "stringer -type CardType"; DO NOT EDIT

package uno

import "fmt"

const _CardTypeName = "CardType0CardType1CardType2CardType3CardType4CardType5CardType6CardType7CardType8CardType9CardTypeSkipCardTypeReverseCardTypeDrawTwoCardTypeWildcardCardTypeWildcardDrawFour"

var _CardTypeIndex = [...]uint8{0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 102, 117, 132, 148, 172}

func (i CardType) String() string {
	if i < 0 || i >= CardType(len(_CardTypeIndex)-1) {
		return fmt.Sprintf("CardType(%d)", i)
	}
	return _CardTypeName[_CardTypeIndex[i]:_CardTypeIndex[i+1]]
}
